Update error message text

diff --git a/admin/add-user b/admin/add-user
--- a/admin/add-user
+++ b/admin/add-user
@@ -8,7 +8,7 @@ if [[ -z "${PICLE_HOME}" ]]; then
     PICLE_HOME="$(cd "$(dirname "$0")" && pwd)/.."
 fi
 source "${PICLE_HOME}/shared/functions.sh" \
-    || (echo "PICLE_HOME is not set!"; exit 1)
+    || (echo "PICLE_HOME is not set or invalid!"; exit 1)
 load_config
 
 if [[ "${#}" -ne 1 ]]; then
